vim.api.nvim_set_var("oceanic_next_terminal_bold", 1)
vim.api.nvim_set_var("oceanic_next_terminal_italic", 1)
-- vim.cmd("colorscheme OceanicNext")
-- vim.cmd("colorscheme dracula")
vim.cmd("colorscheme nightfox")
vim.cmd("colorscheme nightfox")

vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
vim.cmd("hi LineNr guibg=NONE ctermbg=NONE")
vim.cmd("hi SignColumn guibg=NONE ctermbg=NONE")
vim.cmd("hi EndOfBuffer guibg=NONE ctermbg=NONE")
